package com.falanadamian.krim.schedule.domain.model.enumeration;

public enum Position {
    PROFESOR,
    DOKTOR_HABILITOWANY,
    ADIUNKT,
    STARSZY_WYKLADOWCA,
    ASYSTENT,
    WYKLADOWCA,
    DOKTORANT,
    DOKTORANT_ZE_STYPENDIUM,
    DOKTORANT_WDROZENIOWY,
    EKSPERT_DOKTOR,
    EKSPERT_DOKTOR_HABILITOWANY,
    EKSPERT_PROFESOR,
    PROFESOR_ZWYCZAJNY,
    PROFESOR_NADZWYCZAJNY,
    PROFESOR_ZAGRANCZNY
}
